--- 
abstract: Use TT2 syntax to extract data from documents
author: Audrey Tang <cpan@audreyt.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: mit
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Template-Extract
no_index: 
  directory: 
    - inc
    - t
provides: 
  Template::Extract: 
    file: lib/Template/Extract.pm
    version: 0.41
  Template::Extract::Compile: 
    file: lib/Template/Extract/Compile.pm
    version: 0.41
  Template::Extract::Parser: 
    file: lib/Template/Extract/Parser.pm
    version: 0.41
  Template::Extract::Run: 
    file: lib/Template/Extract/Run.pm
    version: 0.41
requires: 
  Template: 2.00
  perl: 5.6.0
version: 0.41
