name: Template-Extract
module_name: Template::Extract
version: 0.31
abstract: Extract data structure from TT2-rendered documents
author: Autrijus Tang (autrijus@autrijus.org)
license: unknown
distribution_type: module
build_requires:
  Test::More: 0
requires:
  Template: 2.00
no_index:
  directory:
    - inc
private:
  directory:
    - inc
generated_by: Module::Install version 0.26
